#cloud-config
hostname: ubuntu-vm
manage_etc_hosts: true
users:
  - name: ubuntu
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOYin02BZc6WNu4v3gKBLBbFVm6LVReQfwn1U77VilGr ubuntuvm
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash