services:
#sdfasdsafasfdsafsad
  tsdproxy_debugger:
    image: alpine:latest
    secrets:
      - tsclientId
      - tsclientSecret
    environment:
      # Tell TSDProxy where to find the secrets (/run/secrets/)
      - TSDCLIENT_ID_FILE=/run/secrets/tsclientId
      - TSDCLIENT_SECRET_FILE=/run/secrets/tsclientSecret
    deploy:
      replicas: 1
    command: > 
      bash -c "cat /run/secrets/tsclientId > TSDCLIENT_ID
      && cat /run/secrets/tsclientSecret > TSDCLIENT_SECRET
      && cat \${TSDCLIENT_ID} \${TSDCLIENT_SECRET}"
secrets:
  tsclientId:
    external: true
  tsclientSecret:
    external: true