services:
#sdfasdsafasfdsafsad
  tsdproxy_debugger:
    image: alpine:latest
    secrets:
      - tsclientId
      - tsclientSecret
    environment:
      # Tell TSDProxy where to find the secrets (mounted by Docker)
      - TSDCLIENT_ID_FILE=/run/secrets/tsclientId
      - TSDCLIENT_SECRET_FILE=/run/secrets/tsclientSecret
    deploy:
      replicas: 1
    command: cat ${TSDCLIENT_ID_FILE} ${TSDCLIENT_SECRET_FILE} && sleep infinity
secrets:
  tsclientId:
    external: true
  tsclientSecret:
    external: true