#curl https://machinename.tailnet.ts.net:8151
# or
#curl http://tsdproxy-mapper.tailnet.ts.net 
# to access nginx web interface
services:
    nginx:
        restart: unless-stopped
        container_name: tester-nginx
        ports:
            - 8151:80 # Nginx web interface (port 8151 on host maps to port 80 in container)
        labels:
            - tsdproxy.enable=true
            - tsdproxy.ephemeral=false
        image: nginx:latest
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf:ro
